# Prevents installation of packages newer than 7 days
# to mitigate supply chain security risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled

# Allow build scripts for trusted dependencies
# - https://pnpm.io/settings#onlybuiltdependencies
onlyBuiltDependencies:
  - unrs-resolver

# Fail on pnpm ignored build scripts
# - https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
