onlyBuiltDependencies:
  - sharp
  - unrs-resolver
# Prevents installation of packages newer than 7 days
# to mitigate supply chain security risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@upleveled/*"
  - eslint-config-upleveled
  - stylelint-config-upleveled
# Fail on pnpm ignored build scripts
# - https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true

# Prevent trust level decreases with new versions of dependencies
# - https://pnpm.io/settings#trustpolicy
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  # first version with provenance: semver@7.5.1
  - semver@6.3.1
